export const validationStrings = {
    EMAIL_ALREADY_REGISTERED: 'Email is already registered.',
    EMAIL_INVALID: 'Email is invalid.',
    EMAIL_NOT_REGISTERED: 'Email is not registered.',
    EMAIL_REQUIRED: 'Email is required.',
    PASSWORD_INVALID: 'Password is invalid.',
    PASSWORD_REQUIRED: 'Password is required.',
    RESOURCE_NOT_FOUND: 'Resource not found.',
    TOKEN_DOES_NOT_EXIST: 'Token does not exist.',
    TOKEN_INVALID: 'Token is invalid.',
    TOKEN_NOT_FOUND_IN_AUTH_HEADER: 'Token not found in authorization header.',
    USER_ID_INVALID: 'User ID is invalid.',
    USERNAME_ALREADY_REGISTERED: 'Username is already registered.',
    USERNAME_NOT_REGISTERED: 'Username is not registered.',
    USERNAME_REQUIRED: 'Username is required.',
};
